### ISSUE TITLE
It is not possible to enter the world after replacing the Quilt version.

### ISSUE THREAD

**Issue by sssHpion007** [frikinjay/quilted-fabric-api#1]
NEC reported that there were problems between the mods Quilt Lifecycle Events and Minecraft Comes Alive
https://crashy.net/qsTtqTBqkUlj8Tv54JW1

**Comment by frikinjay** [comment]
Can I take a look at the raw logs?
Also what exactly do you mean by replacing the quilt version? Did you change the quilt loader version or replace the official quilt jar with this one?

**Comment by sssHpion007** [comment]
I replaced the official version with biomfix version
[crash-2022-08-25_10.32.23-server.txt](https://github.com/frikinjay/quilted-fabric-api/files/9426867/crash-2022-08-25_10.32.23-server.txt)

**Comment by frikinjay** [comment]
Doesnt seem to be crashing on my end with just QFAPI-biomefix and MCA. You probably have a mod conflicting with MCA, I suggest reporting this to the mods devs.

**Comment by sssHpion007** [comment]
Okay, thanks
