### ISSUE TITLE
[Feature Request] 1.19.* Update?

### ISSUE THREAD

**Issue by OCsonic** [frikinjay/quilted-fabric-api#3]
There are some mods that still are not planning to support Quilt, 1.19+ support would be really nice

**Comment by frikinjay** [comment]
Can I get a list of the said mods? No promises and highly likely I wont get time for this but if free i might look into it.

**Comment by OCsonic** [comment]
One of the big ones is Meteor client (I wouldn't be surprised if it's not possible to get working without direct alterations to Meteor itself but I'm hopeful that it is possible), since a lot of utility mods (libzoomer/ok zoomer for example) are moving to Quilt, Meteor is left incompatible with lots of them now (and Meteor is currently the only fully featured client that I can pair with utility mods when playing on anarchy servers)

(There are also other mods, but Meteor is the most important one to get working on Quilt for me)

**Comment by frikinjay** [comment]
Sorry I dont really have any plans to support clients rn or moving this further to 1.19 as most of the mods that needed this have moved to proper way of doing things when they ported to 1.19. You should let the mod devs know to not use unintended fabric classes.

**Comment by OCsonic** [comment]
> Sorry I dont really have any plans to support clients rn or moving this further to 1.19 as most of the mods that needed this have moved to proper way of doing things when they ported to 1.19. You should let the mod devs know to not use unintended fabric classes.

I tried to get it resolved on their end but they are very set in their ways when it comes to supporting Quilt unfortunately. Hopefully something can eventually be done about it.

BTW, Thank you for being reasonable about the suggestion, some people have gotten very rude over suggestions to support clients.
